name: 自用
author: 千亦

fontFace:
- ranges:
  - length: 1      # 定义字体范围的长度
    location: 20013      # 定义字体范围的起始位置
  url: code.ttf      # 字体文件的路径
- ranges:
  - length: 1      # 定义字体范围的长度
    location: 33521      # 定义字体范围的起始位置
  url: code.ttf      # 字体文件的路径
- url: "HYZhengYuan-55W.ttf"
- url: "TumanPUA.ttf"


# 中文键盘
pinyin:
  iPhone:
    portrait: pinyin_26_portrait
    landscape: pinyin_26_landscape

# 英文键盘
alphabetic:
  iPhone:
    portrait: alphabetic_26_portrait
    landscape: pinyin_26_landscape

# 数字键盘
numeric:
  iPhone:
    portrait: numeric_9_portrait
    landscape: numeric_9_landscape

# 符号键盘
symbolic:
  iPhone:
    portrait: symbolic_portrait
    landscape: symbolic_landscape

keySounds:
  - inputKeySound: "sounds/click.m4a"
  - deleteKeySound: "sounds/delete.m4a"
  - { action: space, url: "sounds/modifier.m4a" }
  - { action: {shortcutCommand: "#左移"}, url: "sounds/modifier.m4a" }
  - { action: {shortcutCommand: "#右移"}, url: "sounds/modifier.m4a" }
