按键上标前景样式: &ub
  fontSize: 0.88em
  center:
    y: 0.35
  normalColor: F5F5F555
  highlightColor: F5F5F555

按键文字前景样式: &py
  fontSize: 0.75em
  center:
    y: 1.05
  normalColor: F5F5F5
  highlightColor: F5F5F5

keyboardLayout:
  - HStack:
      subviews:
        - Cell: hamsterButton
        - Cell: uploadButton
        - Cell: scriptButton
        - Cell: fileButton
  - HStack:
      subviews:
        - Cell: skinButton
        - Cell: soundsButton
        - Cell: backupButton
        - Cell: deployButton

floatTargetScale:
  x: 0.62
  y: 0.5

keyboardStyle:
  insets: {top: 8, left: 8, bottom: 8, right: 8}
  backgroundStyle: keyboardBackgroundStyle

keyboardBackgroundStyle:
  type: original
  normalColor: 1a1a1add
  cornerRadius: 15
  borderSize: 0.5
  normalBorderColor: 22222255
  normalLowerEdgeColor: 55555555

hamsterButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - hamsterButtonForegroundStyle1
    - hamsterButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/main}

hamsterButtonForegroundStyle1:
  animation: animation
  systemImageName: keyboard
  <<: *ub

hamsterButtonForegroundStyle2:
  animation: animation
  text: 设置
  <<: *py

uploadButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - uploadButtonForegroundStyle1
    - uploadButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/uploadInputSchema}

uploadButtonForegroundStyle1:
  animation: animation
  systemImageName: wifi
  <<: *ub

uploadButtonForegroundStyle2:
  animation: animation
  text: 上传
  <<: *py

soundsButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - soundsButtonForegroundStyle1
    - soundsButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/feedback}

soundsButtonForegroundStyle1:
  animation: animation
  systemImageName: speaker.wave.2
  <<: *ub

soundsButtonForegroundStyle2:
  animation: animation
  text: 声音
  <<: *py

scriptButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - scriptButtonForegroundStyle1
    - scriptButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/clipboard?type=script}

scriptButtonForegroundStyle1:
  animation: animation
  systemImageName: terminal
  <<: *ub

scriptButtonForegroundStyle2:
  animation: animation
  text: 脚本
  <<: *py

skinButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - skinButtonForegroundStyle1
    - skinButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/keyboardSkins}

skinButtonForegroundStyle1:
  animation: animation
  systemImageName: tshirt
  <<: *ub

skinButtonForegroundStyle2:
  animation: animation
  text: 皮肤
  <<: *py

fileButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - fileButtonForegroundStyle1
    - fileButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/finder}

fileButtonForegroundStyle1:
  animation: animation
  systemImageName: folder
  <<: *ub

fileButtonForegroundStyle2:
  animation: animation
  text: 文件
  <<: *py

backupButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - backupButtonForegroundStyle1
    - backupButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/backup}

backupButtonForegroundStyle1:
  animation: animation
  systemImageName: person.icloud
  <<: *ub

backupButtonForegroundStyle2:
  animation: animation
  text: 备份
  <<: *py

deployButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - deployButtonForegroundStyle1
    - deployButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/rime?deploy}

deployButtonForegroundStyle1:
  animation: animation
  systemImageName: arrow.2.circlepath
  <<: *ub

deployButtonForegroundStyle2:
  animation: animation
  text: 部署
  <<: *py

# 按键背景
ButtonBackgroundStyle:
  animation: animation
  normalImage:
    file: 26key
    image: IMG1
  highlightImage:
    file: 26key_press
    image: IMG1
  targetScale: 0.89

# 动画
animation:
  - type: bounds
    duration: 60 # 动画时长，单位毫秒
    repeatCount: 1
    fromScale: 1
    toScale: 0.87
  - type: bounds
    duration: 80
    repeatCount: 1
    fromScale: 0.87
    toScale: 1
